language: python

services:
  - docker

before_install:
  - docker-compose build
# command to run tests
script:
  - docker-compose run --rm web pytest
# send coverage report to coveralls
after_success:
  coveralls