language: python
cache: pip
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - pytest
# send coverage report to coveralls
after_success:
  coveralls